version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: sinon
        versions:
          - 11.0.0
          - 11.1.0
      - dependency-name: mongoose
        versions:
          - 5.12.10
          - 5.12.11
          - 5.12.5
          - 5.12.6
          - 5.12.7
          - 5.12.8
          - 5.12.9
      - dependency-name: mongodb
        versions:
          - 3.6.7
          - 3.6.8
      - dependency-name: ts-loader
        versions:
          - 9.2.0
          - 9.2.1
      - dependency-name: webpack
        versions:
          - 5.37.1
      - dependency-name: "@boklisten/bl-model"
        versions:
          - 0.25.3
      - dependency-name: "@types/chai"
        versions:
          - 4.2.17
          - 4.2.18
      - dependency-name: eslint
        versions:
          - 7.25.0
          - 7.26.0
      - dependency-name: validator
        versions:
          - 13.6.0
      - dependency-name: redis
        versions:
          - 3.1.2
      - dependency-name: grunt-webpack
        versions:
          - 4.0.3
      - dependency-name: html-pdf
        versions:
          - 3.0.0
      - dependency-name: chalk
        versions:
          - 4.1.1
      - dependency-name: "@types/mongoose"
        versions:
          - 5.10.5
      - dependency-name: grunt
        versions:
          - 1.4.0
