
version: 2
jobs:
  test:
    working_directory: ~/bl-api
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - run:
          name: Node version
          command: "node --version"
      - run:
          name: Npm version
          command: "npm --version"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Install node modules
          command: npm install
      - run:
          name: Test
          command: npm run test
      - run:
          name: Code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-coverage.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
workflows:
  version: 2
  test:
    jobs:
      - test 
