
version: 2
jobs:
  build:
    working_directory: ~/bl-api
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - run:
          name: Node version
          command: "node --version"
      - run:
          name: Npm version
          command: "npm --version"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Typescript
          command: "npm install typescript"
      - run: 
          name: Install node modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
              - node_modules
  test:
    working_directory: ~/bl-api
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-coverage.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
