version: 2
jobs:
  test:
    working_directory: ~/bl-api
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Node version
          command: "node --version"
      - run:
          name: Npm version
          command: "npm --version"
      - run:
          name: Current time
          command: "date"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm ci
      - run:
          name: Test
          command: npm run test
workflows:
  version: 2
  test:
    jobs:
      - test
